coverage:
  status:
    project:
      default:
        target: 40%
        threshold: 2%
    patch:
      default:
        target: 40%
        threshold: 5%
ignore:
  - "cmd/**/*"  # CLI commands are difficult to unit test
comment:
  layout: "reach,diff,flags,files"
  behavior: default
